export const assassinSkills = [
  {
    id: 246,
    name: "药草治疗",
    level: 10,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3455,
    name: "进击斩",
    level: 40,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3385,
    name: "纹样刻印",
    level: 10,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3374,
    name: "纹样爆炸",
    level: 10,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3417,
    name: "猛兽的咆哮",
    level: 20,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3331,
    name: "影分身",
    level: 70,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3355,
    name: "神速之契约",
    level: 20,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3283,
    name: "古代纹样刻印",
    level: 40,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3328,
    name: "回避之契约",
    level: 50,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3406,
    name: "空中捕获",
    level: 70,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3356,
    name: "暗袭",
    level: 30,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3482,
    name: "旋风斩",
    level: 50,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3427,
    name: "猛兽的后踢",
    level: 20,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3339,
    name: "看破之眼",
    level: 40,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3470,
    name: "暗破",
    level: 30,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3491,
    name: "影子披风",
    level: 10,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3338,
    name: "烟幕弹",
    level: 50,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3435,
    name: "猛兽拍击",
    level: 40,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3500,
    name: "螺旋斩",
    level: 50,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 283,
    name: "解除冲击",
    level: 40,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3365,
    name: "猛兽之牙",
    level: 50,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3308,
    name: "沉默纹样爆炸",
    level: 50,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3469,
    name: "强袭姿态",
    level: 40,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3404,
    name: "猛兽跳跃",
    level: 60,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3306,
    name: "交叉斩",
    level: 60,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3478,
    name: "连杀",
    level: 60,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3415,
    name: "灭亡",
    level: 30,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3370,
    name: "变身：残暴处决者",
    level: 50,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3371,
    name: "变身：残暴处决者",
    level: 50,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3340,
    name: "后方斩",
    level: 20,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3271,
    name: "后方打击",
    level: 50,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3441,
    name: "暗影神行",
    level: 50,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5093,
    name: "纹样大爆发",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5094,
    name: "纹样破坏",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5095,
    name: "旋风斩击",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5096,
    name: "旋风连斩",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5097,
    name: "迅速猛袭",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5098,
    name: "迅速强袭",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5170,
    name: "连斩",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5255,
    name: "强化连斩",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5256,
    name: "魂灭",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5277,
    name: "猛兽奇袭",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5278,
    name: "击破奇袭",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5738,
    name: "（提高）纹样大爆发",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5739,
    name: "（提高）纹样破坏",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5740,
    name: "（提高）旋风斩击",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5741,
    name: "（提高）旋风连斩",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5742,
    name: "（提高）迅速猛袭",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5743,
    name: "（提高）迅速强袭",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5744,
    name: "（提高）强化连斩",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5745,
    name: "（提高）魂灭",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5746,
    name: "（提高）猛兽奇袭",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5747,
    name: "（提高）击破奇袭",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5977,
    name: "抵抗之影",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5978,
    name: "神速之影",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5979,
    name: "（增强）抵抗之影",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 5980,
    name: "（增强）神速之影",
    level: 80,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 6695,
    name: "强化隐身 II",
    level: 84,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 6696,
    name: "强化烟幕弹",
    level: 84,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 6697,
    name: "强化进击斩",
    level: 84,
    type: "使用",
    role: ["杀星"],
  },
  {
    id: 3182,
    name: "无刀刃",
    level: 1,
    type: "使用",
    role: ["杀星", "弓星"],
  },
  {
    id: 3195,
    name: "集中回避",
    level: 1,
    type: "使用",
    role: ["杀星", "弓星"],
  },
  {
    id: 3196,
    name: "奇袭",
    level: 3,
    type: "使用",
    role: ["杀星", "弓星"],
  },
  {
    id: 3209,
    name: "反击",
    level: 5,
    type: "使用",
    role: ["杀星", "弓星"],
  },
  {
    id: 3222,
    name: "隐身",
    level: 5,
    type: "使用",
    role: ["杀星", "弓星"],
  },
  {
    id: 3223,
    name: "绝魂斩",
    level: 6,
    type: "使用",
    role: ["杀星", "弓星"],
  },
  {
    id: 3235,
    name: "专注",
    level: 6,
    type: "使用",
    role: ["杀星", "弓星"],
  },
  {
    id: 3396,
    name: "连锁纹样刻印",
    level: 20,
    type: "普通烙印之石",
    role: ["杀星"],
  },
  {
    id: 3320,
    name: "觉悟",
    level: 20,
    type: "普通烙印之石",
    role: ["杀星"],
  },
  {
    id: 3480,
    name: "命中之契约",
    level: 20,
    type: "普通烙印之石",
    role: ["杀星"],
  },
  {
    id: 3329,
    name: "影子步行",
    level: 20,
    type: "普通烙印之石",
    role: ["杀星"],
  },
  {
    id: 3330,
    name: "影子下坠",
    level: 20,
    type: "普通烙印之石",
    role: ["杀星"],
  },
  {
    id: 3255,
    name: "雾砂攻击",
    level: 20,
    type: "普通烙印之石",
    role: ["杀星"],
  },
  {
    id: 3312,
    name: "愤怒之眼",
    level: 20,
    type: "普通烙印之石",
    role: ["杀星"],
  },
  {
    id: 3262,
    name: "远距离纹样刻印",
    level: 20,
    type: "普通烙印之石",
    role: ["杀星"],
  },
  {
    id: 3445,
    name: "后方重击",
    level: 20,
    type: "普通烙印之石",
    role: ["杀星"],
  },
  {
    id: 3313,
    name: "闪电斩",
    level: 45,
    type: "上级烙印之石",
    role: ["杀星"],
  },
  {
    id: 3321,
    name: "涂毒",
    level: 45,
    type: "上级烙印之石",
    role: ["杀星"],
  },
  {
    id: 3332,
    name: "奇袭斩",
    level: 45,
    type: "上级烙印之石",
    role: ["杀星"],
  },
  {
    id: 3249,
    name: "连锁纹样爆炸",
    level: 45,
    type: "上级烙印之石",
    role: ["杀星"],
  },
  {
    id: 3327,
    name: "逃跑姿态",
    level: 45,
    type: "上级烙印之石",
    role: ["杀星"],
  },
  {
    id: 3319,
    name: "六感最大化",
    level: 45,
    type: "上级烙印之石",
    role: ["杀星"],
  },
  {
    id: 3246,
    name: "昏厥之刃",
    level: 55,
    type: "最高级烙印之石",
    role: ["杀星"],
  },
  {
    id: 3245,
    name: "匕首誓约",
    level: 55,
    type: "最高级烙印之石",
    role: ["杀星"],
  },
  {
    id: 3239,
    name: "闪电暗袭",
    level: 55,
    type: "秘传烙印之石",
    role: ["杀星"],
  },
  {
    id: 3242,
    name: "纹样再刻印",
    level: 55,
    type: "秘传烙印之石",
    role: ["杀星"],
  },
  {
    id: 3236,
    name: "闪光弹",
    level: 55,
    type: "秘传烙印之石",
    role: ["杀星"],
  },
];
