export const chanterSkills = [
  {
    id: 246,
    name: "药草治疗",
    level: 10,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1685,
    name: "保护之祝愿",
    level: 10,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1699,
    name: "复活之光",
    level: 30,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 283,
    name: "解除冲击",
    level: 40,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1638,
    name: "神圣保护",
    level: 50,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1602,
    name: "气力重生",
    level: 60,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1657,
    name: "盾牌之真言",
    level: 20,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1809,
    name: "疾走之真言",
    level: 10,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1714,
    name: "不败之真言",
    level: 50,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1759,
    name: "十字防御",
    level: 40,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1637,
    name: "突破之咒语",
    level: 60,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1627,
    name: "大地之约定",
    level: 40,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1715,
    name: "避雷击",
    level: 40,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1596,
    name: "贯穿连锁",
    level: 10,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1769,
    name: "裂破击",
    level: 50,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1875,
    name: "破裂击",
    level: 30,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1700,
    name: "粉碎一击",
    level: 30,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1690,
    name: "保护阵",
    level: 10,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1810,
    name: "疾风之咒语",
    level: 10,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1768,
    name: "连续击破",
    level: 10,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1601,
    name: "力量释放",
    level: 70,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1798,
    name: "振动连锁",
    level: 50,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1580,
    name: "共鸣烟雾",
    level: 30,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1562,
    name: "击破连锁",
    level: 10,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1757,
    name: "时空逃脱",
    level: 70,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1858,
    name: "痊愈之咒语",
    level: 20,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1639,
    name: "强力击",
    level: 20,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1703,
    name: "分裂一击",
    level: 20,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1667,
    name: "白热一击",
    level: 30,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1778,
    name: "流星一击",
    level: 10,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1758,
    name: "神速之咒语",
    level: 50,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 4685,
    name: "阻断之幕",
    level: 50,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5111,
    name: "贯通波",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5112,
    name: "贯通·猛",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5113,
    name: "痊愈之净化咒语",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5114,
    name: "痊愈之保护咒语",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5115,
    name: "连环斩",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5116,
    name: "连续猛击",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5175,
    name: "共鸣悲雾",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5265,
    name: "强化共鸣悲雾",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5266,
    name: "共鸣连斩",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5281,
    name: "魂碎击",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5282,
    name: "斩碎击",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5768,
    name: "（提高）贯通波",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5769,
    name: "（提高）贯通·猛",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5770,
    name: "（提高）痊愈之净化咒语",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5771,
    name: "（提高）痊愈之保护咒语",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5772,
    name: "（提高）连环斩",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5773,
    name: "（提高）连续猛击",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5774,
    name: "（提高）强化共鸣悲雾",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5775,
    name: "（提高）共鸣连斩",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5776,
    name: "（提高）魂碎击",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5777,
    name: "（提高）斩碎击",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5993,
    name: "恢复守护阵",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5994,
    name: "抵抗守护阵",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5995,
    name: "（增强）恢复守护阵",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 5996,
    name: "（增强）抵抗守护阵",
    level: 80,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 4012,
    name: "大地的报应",
    level: 10,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1684,
    name: "保护祝福",
    level: 10,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1814,
    name: "天罚",
    level: 10,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 6692,
    name: "强化强力击",
    level: 84,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 6693,
    name: "强化气力重生",
    level: 84,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 6694,
    name: "强化阻断之幕",
    level: 84,
    type: "使用",
    role: ["护法星"],
  },
  {
    id: 1684,
    name: "保护祝福",
    level: 5,
    type: "使用",
    role: ["治愈星", "护法星"],
  },
  {
    id: 1614,
    name: "断罪一击",
    level: 3,
    type: "使用",
    role: ["治愈星", "护法星"],
  },
  {
    id: 1838,
    name: "治愈之光",
    level: 1,
    type: "使用",
    role: ["治愈星", "护法星"],
  },
  {
    id: 4012,
    name: "大地的报应",
    level: 1,
    type: "使用",
    role: ["治愈星", "护法星"],
  },
  {
    id: 1814,
    name: "天罚",
    level: 6,
    type: "使用",
    role: ["治愈星", "护法星"],
  },
  {
    id: 1756,
    name: "守护之祝福",
    level: 45,
    type: "上级烙印之石",
    role: ["护法星"],
  },
  {
    id: 1801,
    name: "疾行激励",
    level: 20,
    type: "普通烙印之石",
    role: ["护法星"],
  },
  {
    id: 1651,
    name: "风之祝福",
    level: 45,
    type: "上级烙印之石",
    role: ["护法星"],
  },
  {
    id: 1576,
    name: "鼓吹之咒语",
    level: 20,
    type: "普通烙印之石",
    role: ["护法星"],
  },
  {
    id: 1755,
    name: "守护之咒语",
    level: 45,
    type: "上级烙印之石",
    role: ["护法星"],
  },
  {
    id: 1832,
    name: "铁壁之咒语",
    level: 55,
    type: "最高级烙印之石",
    role: ["护法星"],
  },
  {
    id: 1727,
    name: "生命之咒语",
    level: 20,
    type: "普通烙印之石",
    role: ["护法星"],
  },
  {
    id: 1869,
    name: "破散击",
    level: 45,
    type: "上级烙印之石",
    role: ["护法星"],
  },
  {
    id: 1607,
    name: "气概",
    level: 20,
    type: "普通烙印之石",
    role: ["护法星"],
  },
  {
    id: 1863,
    name: "波动攻击",
    level: 45,
    type: "上级烙印之石",
    role: ["护法星"],
  },
  {
    id: 1835,
    name: "冲击锁",
    level: 55,
    type: "最高级烙印之石",
    role: ["护法星"],
  },
  {
    id: 1760,
    name: "暗击锁",
    level: 20,
    type: "普通烙印之石",
    role: ["护法星"],
  },
  {
    id: 1790,
    name: "流水攻击",
    level: 20,
    type: "普通烙印之石",
    role: ["护法星"],
  },
  {
    id: 1852,
    name: "痊愈之手",
    level: 45,
    type: "上级烙印之石",
    role: ["护法星"],
  },
  {
    id: 1883,
    name: "爆裂",
    level: 20,
    type: "普通烙印之石",
    role: ["护法星"],
  },
  {
    id: 1640,
    name: "灭火",
    level: 20,
    type: "普通烙印之石",
    role: ["护法星"],
  },
  {
    id: 1901,
    name: "狂风击",
    level: 55,
    type: "秘传烙印之石",
    role: ["护法星"],
  },
  {
    id: 1904,
    name: "烙印咒语",
    level: 55,
    type: "秘传烙印之石",
    role: ["护法星"],
  },
  {
    id: 1907,
    name: "煽动咒语",
    level: 55,
    type: "秘传烙印之石",
    role: ["护法星"],
  },
  {
    id: 4615,
    name: "绝命重击",
    level: 20,
    type: "普通烙印之石",
    role: ["护法星"],
  },
  {
    id: 4631,
    name: "吸收之咒语",
    level: 20,
    type: "普通烙印之石",
    role: ["护法星"],
  },
];
