export const clericSkills = [
  {
    id: 1684,
    name: "保护祝福",
    level: 5,
    type: "使用",
    role: ["治愈星", "护法星"],
  },
  {
    id: 1614,
    name: "断罪一击",
    level: 3,
    type: "使用",
    role: ["治愈星", "护法星"],
  },
  {
    id: 1838,
    name: "治愈之光",
    level: 1,
    type: "使用",
    role: ["治愈星", "护法星"],
  },
  {
    id: 4012,
    name: "大地的报应",
    level: 1,
    type: "使用",
    role: ["治愈星", "护法星"],
  },
  {
    id: 1814,
    name: "天罚",
    level: 6,
    type: "使用",
    role: ["治愈星", "护法星"],
  },
  {
    id: 283,
    name: "解除冲击",
    level: 40,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 3888,
    name: "神速之祈祷",
    level: 30,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 3889,
    name: "集中的祈祷",
    level: 60,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 3895,
    name: "暴风之祈祷",
    level: 50,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 3912,
    name: "治疗保护膜",
    level: 50,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 3918,
    name: "不灭之帐幕",
    level: 50,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 3922,
    name: "救援",
    level: 10,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 3935,
    name: "净化之光",
    level: 10,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 3938,
    name: "净化之光辉",
    level: 60,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 3951,
    name: "痊愈之闪光",
    level: 50,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 3977,
    name: "治愈的光辉",
    level: 20,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4004,
    name: "召唤复活",
    level: 70,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4005,
    name: "幻生之手",
    level: 50,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4037,
    name: "放电",
    level: 30,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4046,
    name: "大地的惩罚",
    level: 10,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4054,
    name: "雷电",
    level: 20,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4061,
    name: "惩罚之电",
    level: 10,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4073,
    name: "闪电",
    level: 30,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4083,
    name: "大地之怒",
    level: 30,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4098,
    name: "保护之帐幕",
    level: 50,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4105,
    name: "召唤:神圣气息",
    level: 20,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4106,
    name: "召唤:神圣气息",
    level: 20,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4127,
    name: "束缚",
    level: 20,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4128,
    name: "惩罚",
    level: 10,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4150,
    name: "权能爆发",
    level: 40,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4170,
    name: "破灭之诉说",
    level: 10,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4176,
    name: "痊愈之光辉",
    level: 40,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4203,
    name: "治愈的恩宠",
    level: 40,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4213,
    name: "痊愈之光",
    level: 40,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4220,
    name: "免罪",
    level: 50,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 1699,
    name: "复活之光",
    level: 20,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 246,
    name: "药草治疗",
    level: 10,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5105,
    name: "痊愈之净化闪光",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5106,
    name: "痊愈之巨大闪光",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5107,
    name: "电触",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5108,
    name: "持续放电",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5109,
    name: "不灭防壁",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5110,
    name: "不灭保护膜",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5174,
    name: "天雷",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5263,
    name: "强化天雷",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5264,
    name: "连续降雷",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5283,
    name: "疾速之光",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5284,
    name: "痊愈恢复",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5758,
    name: "（提高）痊愈之净化闪光",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5759,
    name: "（提高）痊愈之巨大闪光",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5760,
    name: "（提高）电触",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5761,
    name: "（增强）持续放电",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5762,
    name: "（提高）不灭防壁",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5763,
    name: "（提高）不灭保护膜",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5764,
    name: "（提高）强化天雷",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5765,
    name: "（提高）连续降雷",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5766,
    name: "（提高）疾速之光",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5767,
    name: "（提高）痊愈恢复",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5989,
    name: "迅速救援",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5990,
    name: "铁壁救援",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5991,
    name: "（增强）迅速救援",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 5992,
    name: "（增强）铁壁救援",
    level: 80,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 4012,
    name: "大地的报应",
    level: 10,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 1614,
    name: "断罪一击",
    level: 10,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 6689,
    name: "强化治愈的恩宠",
    level: 84,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 6690,
    name: "强化权能强击",
    level: 84,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 6691,
    name: "强化暴风之祈祷",
    level: 84,
    type: "使用",
    role: ["治愈星"],
  },
  {
    id: 3896,
    name: "破坏之权能",
    level: 45,
    type: "上级烙印之石",
    role: ["治愈星"],
  },
  {
    id: 3903,
    name: "全力疾行",
    level: 20,
    type: "普通烙印之石",
    role: ["治愈星"],
  },
  {
    id: 3904,
    name: "终结的交换",
    level: 20,
    type: "普通烙印之石",
    role: ["治愈星"],
  },
  {
    id: 3924,
    name: "拯救之手",
    level: 20,
    type: "普通烙印之石",
    role: ["治愈星"],
  },
  {
    id: 3960,
    name: "交感治疗",
    level: 20,
    type: "普通烙印之石",
    role: ["治愈星"],
  },
  {
    id: 3980,
    name: "召唤:治愈之气息",
    level: 45,
    type: "上级烙印之石",
    role: ["治愈星"],
  },
  {
    id: 3981,
    name: "召唤:治愈之气息",
    level: 45,
    type: "上级烙印之石",
    role: ["治愈星"],
  },
  {
    id: 3992,
    name: "净化之水",
    level: 45,
    type: "上级烙印之石",
    role: ["治愈星"],
  },
  {
    id: 3998,
    name: "再生之光辉",
    level: 45,
    type: "上级烙印之石",
    role: ["治愈星"],
  },
  {
    id: 4134,
    name: "恢复阻断",
    level: 20,
    type: "普通烙印之石",
    role: ["治愈星"],
  },
  {
    id: 4135,
    name: "闪光",
    level: 20,
    type: "普通烙印之石",
    role: ["治愈星"],
  },
  {
    id: 4136,
    name: "报应之电",
    level: 20,
    type: "普通烙印之石",
    role: ["治愈星"],
  },
  {
    id: 4144,
    name: "痛苦连锁",
    level: 45,
    type: "上级烙印之石",
    role: ["治愈星"],
  },
  {
    id: 4152,
    name: "召唤:高洁气息",
    level: 45,
    type: "上级烙印之石",
    role: ["治愈星"],
  },
  {
    id: 4153,
    name: "召唤:高洁气息",
    level: 45,
    type: "上级烙印之石",
    role: ["治愈星"],
  },
  {
    id: 4164,
    name: "霹雳",
    level: 55,
    type: "最高级烙印之石",
    role: ["治愈星"],
  },
  {
    id: 4182,
    name: "弱化之印",
    level: 20,
    type: "普通烙印之石",
    role: ["治愈星"],
  },
  {
    id: 4188,
    name: "恢复之佑护",
    level: 20,
    type: "普通烙印之石",
    role: ["治愈星"],
  },
  {
    id: 4167,
    name: "审判烙印",
    level: 55,
    type: "秘传烙印之石",
    role: ["治愈星"],
  },
  {
    id: 3906,
    name: "召唤：讨伐气息",
    level: 55,
    type: "秘传烙印之石",
    role: ["治愈星"],
  },
  {
    id: 3907,
    name: "召唤：讨伐气息",
    level: 55,
    type: "秘传烙印之石",
    role: ["治愈星"],
  },
  {
    id: 3932,
    name: "拯救荣耀",
    level: 55,
    type: "秘传烙印之石",
    role: ["治愈星"],
  },
];
