export const gladiatorSkills = [
  {
    id: 246,
    name: "药草治疗",
    level: 10,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 519,
    name: "激怒爆炸",
    level: 10,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 531,
    name: "击破一击",
    level: 40,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 545,
    name: "空中捆绑",
    level: 50,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 554,
    name: "狂刺",
    level: 40,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 555,
    name: "范围波动",
    level: 40,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 2932,
    name: "均衡的盔甲",
    level: 50,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 572,
    name: "气息爆炸",
    level: 60,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 574,
    name: "翅膀强化",
    level: 50,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 2981,
    name: "挑衅",
    level: 10,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 590,
    name: "跳刺",
    level: 30,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 3124,
    name: "突击",
    level: 50,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 598,
    name: "突击姿态",
    level: 40,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 601,
    name: "身体连击",
    level: 20,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 604,
    name: "肉体打击",
    level: 40,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 619,
    name: "防御准备",
    level: 60,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 620,
    name: "复仇之甲",
    level: 70,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 621,
    name: "愤怒爆炸",
    level: 50,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 624,
    name: "愤怒一击",
    level: 20,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 635,
    name: "愤怒波动",
    level: 50,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 644,
    name: "杀气破裂",
    level: 30,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 648,
    name: "生存姿态",
    level: 50,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 663,
    name: "衰弱之猛击",
    level: 10,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 670,
    name: "压力波动",
    level: 20,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 697,
    name: "战斗准备",
    level: 30,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 706,
    name: "集中格挡",
    level: 60,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 707,
    name: "最后一击",
    level: 40,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 283,
    name: "解除冲击",
    level: 40,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 710,
    name: "飞刀",
    level: 10,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 720,
    name: "飞刀连射",
    level: 20,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 725,
    name: "刀刃乱舞",
    level: 30,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 769,
    name: "嗜魂波",
    level: 10,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 4670,
    name: "吸收反击",
    level: 60,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5081,
    name: "杀气吸收",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5082,
    name: "杀气爆发",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5083,
    name: "击破猛击",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5084,
    name: "击破斩击",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5085,
    name: "突击猛势",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5086,
    name: "突击形势",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5168,
    name: "刀刃连舞",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5251,
    name: "强化刀刃连舞",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5252,
    name: "刀刃击破",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5273,
    name: "宽幅强震",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5274,
    name: "斩击跳跃",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5718,
    name: "（提高）杀气吸收",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5719,
    name: "（提高）杀气爆发",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5720,
    name: "（提高）击破猛击",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5721,
    name: "（提高）击破斩击",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5722,
    name: "（提高）突击猛势",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5723,
    name: "（提高）突击形势",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5724,
    name: "（提高）强化刀刃连舞",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5725,
    name: "（提高）刀刃击破",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5726,
    name: "（提高）宽幅强震",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5727,
    name: "（提高）斩击跳跃",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5969,
    name: "狂怒爆炸",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5970,
    name: "激怒释放",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5971,
    name: "（增强）狂怒爆炸",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 5972,
    name: "（增强）激怒释放",
    level: 80,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 2903,
    name: "气合",
    level: 10,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 6684,
    name: "强化吸血波",
    level: 84,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 6687,
    name: "强化均衡的盔甲",
    level: 84,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 6685,
    name: "强化生存姿态",
    level: 84,
    type: "使用",
    role: ["剑星"],
  },
  {
    id: 517,
    name: "剑气挑衅",
    level: 6,
    type: "使用",
    role: ["剑星", "守护星"],
  },
  {
    id: 2864,
    name: "猛烈一击",
    level: 1,
    type: "使用",
    role: ["剑星", "守护星"],
  },
  {
    id: 2877,
    name: "会心一击",
    level: 3,
    type: "使用",
    role: ["剑星", "守护星"],
  },
  {
    id: 2890,
    name: "身体重击",
    level: 5,
    type: "使用",
    role: ["剑星", "守护星"],
  },
  {
    id: 2903,
    name: "气合",
    level: 6,
    type: "使用",
    role: ["剑星", "守护星"],
  },
  {
    id: 500,
    name: "强制捆绑",
    level: 20,
    type: "普通烙印之石",
    role: ["剑星"],
  },
  {
    id: 539,
    name: "枯竭波",
    level: 45,
    type: "上级烙印之石",
    role: ["剑星"],
  },
  {
    id: 564,
    name: "气魄",
    level: 20,
    type: "普通烙印之石",
    role: ["剑星"],
  },
  {
    id: 575,
    name: "下刺",
    level: 20,
    type: "普通烙印之石",
    role: ["剑星"],
  },
  {
    id: 584,
    name: "熟练的反击",
    level: 45,
    type: "上级烙印之石",
    role: ["剑星"],
  },
  {
    id: 600,
    name: "魔力防御",
    level: 20,
    type: "普通烙印之石",
    role: ["剑星"],
  },
  {
    id: 612,
    name: "斩脚",
    level: 45,
    type: "上级烙印之石",
    role: ["剑星"],
  },
  {
    id: 618,
    name: "抓脚",
    level: 20,
    type: "普通烙印之石",
    role: ["剑星"],
  },
  {
    id: 649,
    name: "破坏城门",
    level: 20,
    type: "普通烙印之石",
    role: ["剑星"],
  },
  {
    id: 676,
    name: "锐利一击",
    level: 45,
    type: "上级烙印之石",
    role: ["剑星"],
  },
  {
    id: 683,
    name: "威胁的咆哮",
    level: 20,
    type: "普通烙印之石",
    role: ["剑星"],
  },
  {
    id: 691,
    name: "幻影弹",
    level: 45,
    type: "上级烙印之石",
    role: ["剑星"],
  },
  {
    id: 698,
    name: "地震波动",
    level: 20,
    type: "普通烙印之石",
    role: ["剑星"],
  },
  {
    id: 733,
    name: "破灭之猛击",
    level: 45,
    type: "上级烙印之石",
    role: ["剑星"],
  },
  {
    id: 749,
    name: "重生波",
    level: 45,
    type: "上级烙印之石",
    role: ["剑星"],
  },
  {
    id: 755,
    name: "回旋一击",
    level: 55,
    type: "最高级烙印之石",
    role: ["剑星"],
  },
  {
    id: 761,
    name: "嗜魂戳刺",
    level: 20,
    type: "普通烙印之石",
    role: ["剑星"],
  },
  {
    id: 781,
    name: "烈焰狂刃",
    level: 55,
    type: "最高级烙印之石",
    role: ["剑星"],
  },
  {
    id: 657,
    name: "召唤：战场旗帜",
    level: 55,
    type: "秘传烙印之石",
    role: ["剑星"],
  },
  {
    id: 658,
    name: "召唤：战场旗帜",
    level: 55,
    type: "秘传烙印之石",
    role: ["剑星"],
  },
  {
    id: 727,
    name: "破灭剑气",
    level: 55,
    type: "秘传烙印之石",
    role: ["剑星"],
  },
  {
    id: 641,
    name: "破碎漩涡",
    level: 55,
    type: "秘传烙印之石",
    role: ["剑星"],
  },
];
