export const rangerSkills = [
  {
    id: 246,
    name: "药草治疗",
    level: 10,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 784,
    name: "强袭箭",
    level: 10,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 796,
    name: "强化之眼",
    level: 20,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 809,
    name: "警戒之眼",
    level: 70,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 826,
    name: "格力普尼克斯之箭",
    level: 50,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 830,
    name: "螺旋箭",
    level: 20,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 841,
    name: "大自然的呼吸",
    level: 30,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 867,
    name: "风之疾走",
    level: 60,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 872,
    name: "变身:莱卡恩",
    level: 10,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 889,
    name: "速射之眼",
    level: 20,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 896,
    name: "睡眠箭",
    level: 40,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 906,
    name: "睡眠陷阱",
    level: 50,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 909,
    name: "睡眠陷阱",
    level: 50,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 912,
    name: "瞬影前行",
    level: 60,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 913,
    name: "神速之呼吸",
    level: 60,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 939,
    name: "连射",
    level: 10,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 950,
    name: "套索箭",
    level: 10,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 994,
    name: "阻击",
    level: 10,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 1010,
    name: "精准箭",
    level: 10,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 1022,
    name: "脚镣箭",
    level: 50,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 1054,
    name: "最后重击",
    level: 50,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 283,
    name: "解除冲击",
    level: 40,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 1066,
    name: "沉默箭",
    level: 20,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 1075,
    name: "夺取之箭",
    level: 50,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 1090,
    name: "退步斩",
    level: 40,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 1102,
    name: "破灭箭",
    level: 30,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 1118,
    name: "百发百中",
    level: 30,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 1120,
    name: "降魔之箭",
    level: 50,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 1141,
    name: "泥土陷阱",
    level: 40,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 1148,
    name: "泥土陷阱",
    level: 40,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 3339,
    name: "看破之眼",
    level: 40,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5099,
    name: "脚镣铁箭",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5100,
    name: "脚镣箭雨",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5101,
    name: "破灭箭雨",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5102,
    name: "破灭连射",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5103,
    name: "退步猛击",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5104,
    name: "退步击",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5171,
    name: "沉默短剑投掷",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5257,
    name: "沉默一击",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5258,
    name: "封锁之箭",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5279,
    name: "破坏之箭",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5280,
    name: "必灭之箭",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5748,
    name: "（提高）脚镣铁箭",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5749,
    name: "（提高）脚镣箭雨",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5750,
    name: "（提高）破灭箭雨",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5751,
    name: "（提高）破灭连射",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5752,
    name: "（提高）退步猛击",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5753,
    name: "（提高）退步击",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5754,
    name: "（提高）沉默一击",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5755,
    name: "（提高）封锁之箭",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5756,
    name: "（提高）破坏之箭",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5757,
    name: "（提高）必灭之箭",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5981,
    name: "莱卡恩的荣誉",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5982,
    name: "莱卡恩的荣耀",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5983,
    name: "（增强）莱卡恩的荣誉",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 5984,
    name: "（增强）莱卡恩的荣耀",
    level: 80,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 6698,
    name: "强化隐身 I",
    level: 84,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 6699,
    name: "强化螺旋箭",
    level: 84,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 6700,
    name: "强化大自然的祝福",
    level: 84,
    type: "使用",
    role: ["弓星"],
  },
  {
    id: 3182,
    name: "无刀刃",
    level: 1,
    type: "使用",
    role: ["杀星", "弓星"],
  },
  {
    id: 3195,
    name: "集中回避",
    level: 1,
    type: "使用",
    role: ["杀星", "弓星"],
  },
  {
    id: 3196,
    name: "奇袭",
    level: 3,
    type: "使用",
    role: ["杀星", "弓星"],
  },
  {
    id: 3209,
    name: "反击",
    level: 5,
    type: "使用",
    role: ["杀星", "弓星"],
  },
  {
    id: 3222,
    name: "隐身",
    level: 5,
    type: "使用",
    role: ["杀星", "弓星"],
  },
  {
    id: 3223,
    name: "绝魂斩",
    level: 6,
    type: "使用",
    role: ["杀星", "弓星"],
  },
  {
    id: 3235,
    name: "专注",
    level: 6,
    type: "使用",
    role: ["杀星", "弓星"],
  },
  {
    id: 810,
    name: "痛苦之箭",
    level: 55,
    type: "最高级烙印之石",
    role: ["弓星"],
  },
  {
    id: 813,
    name: "攻击之眼",
    level: 20,
    type: "普通烙印之石",
    role: ["弓星"],
  },
  {
    id: 814,
    name: "狂暴之箭",
    level: 45,
    type: "上级烙印之石",
    role: ["弓星"],
  },
  {
    id: 820,
    name: "狂风箭",
    level: 45,
    type: "上级烙印之石",
    role: ["弓星"],
  },
  {
    id: 849,
    name: "钝化陷阱",
    level: 20,
    type: "普通烙印之石",
    role: ["弓星"],
  },
  {
    id: 857,
    name: "钝化陷阱",
    level: 20,
    type: "普通烙印之石",
    role: ["弓星"],
  },
  {
    id: 869,
    name: "闪电箭",
    level: 55,
    type: "最高级烙印之石",
    role: ["弓星"],
  },
  {
    id: 873,
    name: "封印箭",
    level: 20,
    type: "普通烙印之石",
    role: ["弓星"],
  },
  {
    id: 888,
    name: "猎人的决心",
    level: 45,
    type: "上级烙印之石",
    role: ["弓星"],
  },
  {
    id: 970,
    name: "冤魂陷阱",
    level: 20,
    type: "普通烙印之石",
    role: ["弓星"],
  },
  {
    id: 962,
    name: "冤魂陷阱",
    level: 20,
    type: "普通烙印之石",
    role: ["弓星"],
  },
  {
    id: 978,
    name: "炸裂陷阱",
    level: 20,
    type: "普通烙印之石",
    role: ["弓星"],
  },
  {
    id: 986,
    name: "炸裂陷阱",
    level: 20,
    type: "普通烙印之石",
    role: ["弓星"],
  },
  {
    id: 1009,
    name: "抵抗的决心",
    level: 20,
    type: "普通烙印之石",
    role: ["弓星"],
  },
  {
    id: 1047,
    name: "疾风箭",
    level: 45,
    type: "上级烙印之石",
    role: ["弓星"],
  },
  {
    id: 1057,
    name: "祝福之弓",
    level: 20,
    type: "普通烙印之石",
    role: ["弓星"],
  },
  {
    id: 1101,
    name: "透视陷阱",
    level: 20,
    type: "普通烙印之石",
    role: ["弓星"],
  },
  {
    id: 1100,
    name: "透视陷阱",
    level: 20,
    type: "普通烙印之石",
    role: ["弓星"],
  },
  {
    id: 1112,
    name: "爆炸箭",
    level: 45,
    type: "上级烙印之石",
    role: ["弓星"],
  },
  {
    id: 1126,
    name: "箭矢强化",
    level: 45,
    type: "上级烙印之石",
    role: ["弓星"],
  },
  {
    id: 1127,
    name: "箭雨",
    level: 20,
    type: "普通烙印之石",
    role: ["弓星"],
  },
  {
    id: 1006,
    name: "一箭穿刺",
    level: 55,
    type: "秘传烙印之石",
    role: ["弓星"],
  },
  {
    id: 936,
    name: "影子隐藏",
    level: 55,
    type: "秘传烙印之石",
    role: ["弓星"],
  },
  {
    id: 1060,
    name: "冲突陷阱",
    level: 55,
    type: "秘传烙印之石",
    role: ["弓星"],
  },
  {
    id: 1061,
    name: "冲突陷阱",
    level: 55,
    type: "秘传烙印之石",
    role: ["弓星"],
  },
];
