export const sorcererSkills = [
  {
    id: 1282,
    name: "火箭",
    level: 1,
    type: "使用",
    role: ["魔道星", "精灵星"],
  },
  {
    id: 1328,
    name: "束缚",
    level: 1,
    type: "使用",
    role: ["魔道星", "精灵星"],
  },
  {
    id: 1363,
    name: "冰冻锁链",
    level: 3,
    type: "使用",
    role: ["魔道星", "精灵星"],
  },
  {
    id: 1447,
    name: "侵蚀",
    level: 5,
    type: "使用",
    role: ["魔道星", "精灵星"],
  },
  {
    id: 1155,
    name: "钢铁保护膜",
    level: 6,
    type: "使用",
    role: ["魔道星", "精灵星"],
  },
  {
    id: 246,
    name: "药草治疗",
    level: 10,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1167,
    name: "冬季的束缚",
    level: 30,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1178,
    name: "冬日幻影",
    level: 50,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1179,
    name: "结冰",
    level: 10,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1184,
    name: "空中束缚",
    level: 30,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1217,
    name: "冷气召唤",
    level: 20,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1245,
    name: "鲁米埃尔之震怒",
    level: 50,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1249,
    name: "魔力倍增",
    level: 50,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1250,
    name: "魔力冰刃",
    level: 20,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1258,
    name: "魔力烈焰",
    level: 40,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1259,
    name: "风之枪",
    level: 10,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1270,
    name: "白杰尔的智慧",
    level: 40,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1271,
    name: "火焰叉",
    level: 10,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1338,
    name: "睡眠之云",
    level: 10,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1347,
    name: "时空扭曲",
    level: 20,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1349,
    name: "时空回廊",
    level: 50,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1348,
    name: "时空回廊",
    level: 50,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1385,
    name: "烈火",
    level: 40,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1387,
    name: "灵魂冻结",
    level: 30,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1391,
    name: "灵魂吸收",
    level: 60,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1416,
    name: "诅咒:古树",
    level: 50,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1417,
    name: "诅咒:树",
    level: 10,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1446,
    name: "铁甲之恩惠",
    level: 40,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 283,
    name: "解除冲击",
    level: 40,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1506,
    name: "火山大爆发",
    level: 60,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1510,
    name: "灼伤",
    level: 10,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1526,
    name: "火焰喷射",
    level: 50,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1533,
    name: "火焰熔解",
    level: 20,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1543,
    name: "火焰圆舞曲",
    level: 60,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1549,
    name: "幻影",
    level: 70,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1403,
    name: "爆裂",
    level: 10,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1226,
    name: "冷气波动",
    level: 10,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 17,
    name: "睡眠：稻草人",
    level: 30,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5117,
    name: "召唤热气",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5118,
    name: "发射寒气",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5119,
    name: "魔力激发",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5120,
    name: "魔力爆发",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5121,
    name: "火焰乱射",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5122,
    name: "火焰光线",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5172,
    name: "火山大喷发",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5259,
    name: "强化火山大喷发",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5260,
    name: "地震大爆发",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5285,
    name: "迅疾之枪",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5286,
    name: "时空之枪",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5778,
    name: "（提高）召唤热气",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5779,
    name: "（提高）发射寒气",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5780,
    name: "（提高）魔力激发",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5781,
    name: "（提高）魔力爆炸",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5782,
    name: "（提高）火焰乱射",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5783,
    name: "（提高）火焰光线",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5784,
    name: "（提高）强化火山大喷发",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5785,
    name: "（提高）地震大爆发",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5786,
    name: "（提高）迅疾之枪",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5787,
    name: "（提高）时空之枪",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5997,
    name: "巨大睡眠之云",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5998,
    name: "集中睡眠之云",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 5999,
    name: "（增强）巨大睡眠之云",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 6000,
    name: "（增强）集中睡眠之云",
    level: 80,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1447,
    name: "侵蚀",
    level: 10,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1363,
    name: "冰冻锁链",
    level: 10,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1282,
    name: "火箭",
    level: 10,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 6701,
    name: "强化钢铁护膜",
    level: 84,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 6702,
    name: "强化愤怒烈焰",
    level: 84,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 6703,
    name: "强化冬日幻影",
    level: 84,
    type: "使用",
    role: ["魔道星"],
  },
  {
    id: 1210,
    name: "落雷",
    level: 20,
    type: "普通烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1216,
    name: "冷却",
    level: 20,
    type: "普通烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1305,
    name: "冰雪甲胄",
    level: 55,
    type: "最高级烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1308,
    name: "冰柱",
    level: 20,
    type: "普通烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1316,
    name: "冰柱",
    level: 20,
    type: "普通烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1324,
    name: "冰河重击",
    level: 55,
    type: "最高级烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1327,
    name: "活力交换",
    level: 20,
    type: "普通烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1329,
    name: "衰弱之诅咒",
    level: 20,
    type: "普通烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1339,
    name: "睡眠暴风",
    level: 45,
    type: "上级烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1350,
    name: "神速的恩惠",
    level: 20,
    type: "普通烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1351,
    name: "岩石召唤 I",
    level: 45,
    type: "上级烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1376,
    name: "冰冻之叉",
    level: 20,
    type: "普通烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1402,
    name: "元素结界",
    level: 20,
    type: "普通烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1460,
    name: "召唤台风",
    level: 45,
    type: "上级烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1468,
    name: "召唤台风",
    level: 45,
    type: "上级烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1486,
    name: "暴风重击",
    level: 20,
    type: "普通烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1520,
    name: "火焰乱舞",
    level: 45,
    type: "上级烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1550,
    name: "幻影漩涡",
    level: 45,
    type: "上级烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1540,
    name: "火焰恩惠",
    level: 55,
    type: "秘传烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1418,
    name: "圣域结界",
    level: 55,
    type: "秘传烙印之石",
    role: ["魔道星"],
  },
  {
    id: 1340,
    name: "催眠之风",
    level: 55,
    type: "秘传烙印之石",
    role: ["魔道星"],
  },
  {
    id: 4597,
    name: "风之刃",
    level: 45,
    type: "上级烙印之石",
    role: ["魔道星"],
  },
];
