export const spiritmasterSkills = [
  {
    id: 246,
    name: "药草治疗",
    level: 10,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3780,
    name: "无力的束缚",
    level: 10,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3706,
    name: "召唤:火之精灵",
    level: 10,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3707,
    name: "召唤:火之精灵",
    level: 10,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3603,
    name: "大地之锁链",
    level: 10,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3835,
    name: "命令:爆裂爪",
    level: 50,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3684,
    name: "召唤:风之精灵",
    level: 20,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3685,
    name: "召唤:风之精灵",
    level: 20,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3570,
    name: "魔法解除",
    level: 20,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3644,
    name: "召唤:地之精灵",
    level: 20,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3645,
    name: "召唤:地之精灵",
    level: 20,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3630,
    name: "元素补充",
    level: 20,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3664,
    name: "召唤:水之精灵",
    level: 30,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3665,
    name: "召唤:水之精灵",
    level: 30,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3809,
    name: "召唤:风之气息",
    level: 10,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3810,
    name: "召唤:风之气息",
    level: 10,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3614,
    name: "大地振动",
    level: 10,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3593,
    name: "真空爆炸",
    level: 10,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3532,
    name: "魔法燃烧",
    level: 40,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3742,
    name: "范围侵蚀",
    level: 30,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3777,
    name: "召唤:队员",
    level: 50,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3775,
    name: "灵魂之呼喊",
    level: 20,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3572,
    name: "魔法阻断",
    level: 40,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3837,
    name: "命令:扰乱",
    level: 10,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3779,
    name: "召唤：精灵",
    level: 10,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3781,
    name: "魔法消除",
    level: 10,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3582,
    name: "精灵弱化",
    level: 30,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3730,
    name: "抵抗之契约",
    level: 50,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3589,
    name: "恐怖的呼喊",
    level: 40,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3790,
    name: "诅咒之云",
    level: 50,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 283,
    name: "解除冲击",
    level: 40,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3591,
    name: "诅咒:火之精灵",
    level: 50,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3592,
    name: "诅咒:水之精灵",
    level: 50,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3833,
    name: "命令：保护",
    level: 60,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3782,
    name: "召唤:台风精灵",
    level: 10,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3783,
    name: "召唤:熔岩精灵",
    level: 10,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3640,
    name: "吸引",
    level: 20,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3629,
    name: "消灵咒语",
    level: 50,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3839,
    name: "命令:精灵的庇护",
    level: 60,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3740,
    name: "魔法爆炸",
    level: 70,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3778,
    name: "恶梦束缚",
    level: 40,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3776,
    name: "灵魂抢夺",
    level: 70,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3853,
    name: "命令：压迫气势",
    level: 40,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3602,
    name: "精灵强化：元素盔甲",
    level: 70,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3834,
    name: "元素打击",
    level: 30,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 3838,
    name: "命令：元素风暴",
    level: 70,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 20,
    name: "灵魂之呼喊：人参",
    level: 20,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5123,
    name: "命令：元素破裂",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5124,
    name: "命令：元素波动",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5125,
    name: "噩梦诅咒",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5126,
    name: "噩梦悲叹",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5127,
    name: "真空大爆炸",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5128,
    name: "真空连续爆炸",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5173,
    name: "灵魂摄取",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5261,
    name: "强化灵魂摄取",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5262,
    name: "灵魂燃烧",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5287,
    name: "精灵衰弱",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5288,
    name: "精灵束缚",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5788,
    name: "（提高）命令：元素破裂",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5789,
    name: "（提高）命令：元素波动",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5790,
    name: "（提高）噩梦诅咒",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5791,
    name: "（提高）噩梦悲叹",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5792,
    name: "（提高）真空大爆炸",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5793,
    name: "（提高）真空连续爆炸",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5794,
    name: "（提高）强化灵魂摄取",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5795,
    name: "（提高）灵魂燃烧",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5796,
    name: "（提高）精灵衰弱",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 5797,
    name: "（提高）精灵束缚",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 6001,
    name: "魔法强力消除",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 6002,
    name: "魔法集中消除",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 6003,
    name: "（增强）魔法强力消除",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 6004,
    name: "（增强）魔法集中消除",
    level: 80,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 1282,
    name: "火箭",
    level: 10,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 1363,
    name: "冰冻锁链",
    level: 10,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 1226,
    name: "冷气波动",
    level: 10,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 6701,
    name: "强化钢铁护膜",
    level: 84,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 6704,
    name: "强化魔法燃烧",
    level: 84,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 6705,
    name: "强化范围侵蚀",
    level: 84,
    type: "使用",
    role: ["精灵星"],
  },
  {
    id: 1282,
    name: "火箭",
    level: 1,
    type: "使用",
    role: ["魔道星", "精灵星"],
  },
  {
    id: 1328,
    name: "束缚",
    level: 1,
    type: "使用",
    role: ["魔道星", "精灵星"],
  },
  {
    id: 1363,
    name: "冰冻锁链",
    level: 3,
    type: "使用",
    role: ["魔道星", "精灵星"],
  },
  {
    id: 1447,
    name: "侵蚀",
    level: 5,
    type: "使用",
    role: ["魔道星", "精灵星"],
  },
  {
    id: 1155,
    name: "钢铁保护膜",
    level: 6,
    type: "使用",
    role: ["魔道星", "精灵星"],
  },
  {
    id: 3739,
    name: "精灵的牺牲",
    level: 20,
    type: "普通烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3562,
    name: "大地之守护",
    level: 20,
    type: "普通烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3731,
    name: "魔力诅咒",
    level: 20,
    type: "普通烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3751,
    name: "荒野之怒",
    level: 20,
    type: "普通烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3836,
    name: "命令:毁灭",
    level: 20,
    type: "普通烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3840,
    name: "愤怒之漩涡",
    level: 20,
    type: "普通烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3575,
    name: "黑暗诅咒",
    level: 20,
    type: "普通烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3531,
    name: "命令:守护之墙",
    level: 20,
    type: "普通烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3544,
    name: "隐身之光辉",
    level: 20,
    type: "普通烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3574,
    name: "钝化足镣",
    level: 45,
    type: "上级烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3550,
    name: "魔法逆流",
    level: 45,
    type: "上级烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3556,
    name: "幽冥之苦痛",
    level: 45,
    type: "上级烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3548,
    name: "命令：破灭攻势",
    level: 45,
    type: "上级烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3797,
    name: "召唤:旋风之气息",
    level: 45,
    type: "上级烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3798,
    name: "召唤:旋风之气息",
    level: 45,
    type: "上级烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3590,
    name: "精灵强化:治愈",
    level: 45,
    type: "上级烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3545,
    name: "黄泉之诅咒",
    level: 55,
    type: "最高级烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3796,
    name: "精灵强化:强化甲胄",
    level: 55,
    type: "最高级烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3541,
    name: "精灵合体",
    level: 55,
    type: "秘传烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3849,
    name: "范围吸收",
    level: 55,
    type: "秘传烙印之石",
    role: ["精灵星"],
  },
  {
    id: 3549,
    name: "命令：忠实替身",
    level: 55,
    type: "秘传烙印之石",
    role: ["精灵星"],
  },
];
