import { LibSkill } from "../types";

export const tempArr = [
  [
    246,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--246"><div class="icon_wrapper"><a href="/cn/skill/246/">[img src="/skills/cbt_mending_g2.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/246/" class="qtooltip item_grade_1"  data-id="skill--246"><b>药草治疗</b></a>',
    10,
    "使用",
    "护法星",
    2,
  ],
  [
    1685,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1685"><div class="icon_wrapper"><a href="/cn/skill/1685/">[img src="/skills/cbt_cl_blessofhealth_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1685/" class="qtooltip item_grade_1"  data-id="skill--1685"><b>保护之祝愿</b></a>',
    10,
    "使用",
    "护法星",
    2,
  ],
  [
    1699,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1699"><div class="icon_wrapper"><a href="/cn/skill/1699/">[img src="/skills/cbt_cl_revive_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1699/" class="qtooltip item_grade_1"  data-id="skill--1699"><b>复活之光</b></a>',
    30,
    "使用",
    "护法星",
    2,
  ],
  [
    283,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--283"><div class="icon_wrapper"><a href="/cn/skill/283/">[img src="/skills/live_all_shockreflect_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/283/" class="qtooltip item_grade_1"  data-id="skill--283"><b>解除冲击</b></a>',
    40,
    "使用",
    "护法星",
    2,
  ],
  [
    1638,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1638"><div class="icon_wrapper"><a href="/cn/skill/1638/">[img src="/skills/cbt_ch_abyssgloria_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1638/" class="qtooltip item_grade_1"  data-id="skill--1638"><b>神圣保护</b></a>',
    50,
    "使用",
    "护法星",
    2,
  ],
  [
    1602,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1602"><div class="icon_wrapper"><a href="/cn/skill/1602/">[img src="/skills/live_ch_chakra_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1602/" class="qtooltip item_grade_1"  data-id="skill--1602"><b>气力重生</b></a>',
    60,
    "使用",
    "护法星",
    2,
  ],
  [
    1657,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1657"><div class="icon_wrapper"><a href="/cn/skill/1657/">[img src="/skills/cbt_ch_chant_improveddefend_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1657/" class="qtooltip item_grade_1"  data-id="skill--1657"><b>盾牌之真言</b></a>',
    20,
    "使用",
    "护法星",
    2,
  ],
  [
    1809,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1809"><div class="icon_wrapper"><a href="/cn/skill/1809/">[img src="/skills/cbt_ch_chant_improvedmove_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1809/" class="qtooltip item_grade_1"  data-id="skill--1809"><b>疾走之真言</b></a>',
    10,
    "使用",
    "护法星",
    2,
  ],
  [
    1714,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1714"><div class="icon_wrapper"><a href="/cn/skill/1714/">[img src="/skills/live_ch_chant_invincible_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1714/" class="qtooltip item_grade_1"  data-id="skill--1714"><b>不败之真言</b></a>',
    50,
    "使用",
    "护法星",
    2,
  ],
  [
    1759,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1759"><div class="icon_wrapper"><a href="/cn/skill/1759/">[img src="/skills/live_ch_crossparry_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1759/" class="qtooltip item_grade_1"  data-id="skill--1759"><b>十字防御</b></a>',
    40,
    "使用",
    "护法星",
    2,
  ],
  [
    1637,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1637"><div class="icon_wrapper"><a href="/cn/skill/1637/">[img src="/skills/live_ch_frontalattack_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1637/" class="qtooltip item_grade_1"  data-id="skill--1637"><b>突破之咒语</b></a>',
    60,
    "使用",
    "护法星",
    2,
  ],
  [
    1627,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1627"><div class="icon_wrapper"><a href="/cn/skill/1627/">[img src="/skills/cbt_ch_imbueearth_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1627/" class="qtooltip item_grade_1"  data-id="skill--1627"><b>大地之约定</b></a>',
    40,
    "使用",
    "护法星",
    2,
  ],
  [
    1715,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1715"><div class="icon_wrapper"><a href="/cn/skill/1715/">[img src="/skills/live_ch_lightningstrike_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1715/" class="qtooltip item_grade_1"  data-id="skill--1715"><b>避雷击</b></a>',
    40,
    "使用",
    "护法星",
    2,
  ],
  [
    1596,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1596"><div class="icon_wrapper"><a href="/cn/skill/1596/">[img src="/skills/cbt_ch_mortalstrike_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1596/" class="qtooltip item_grade_1"  data-id="skill--1596"><b>贯穿连锁</b></a>',
    10,
    "使用",
    "护法星",
    2,
  ],
  [
    1769,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1769"><div class="icon_wrapper"><a href="/cn/skill/1769/">[img src="/skills/cbt_ch_parryingstrike_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1769/" class="qtooltip item_grade_1"  data-id="skill--1769"><b>裂破击</b></a>',
    50,
    "使用",
    "护法星",
    2,
  ],
  [
    1875,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1875"><div class="icon_wrapper"><a href="/cn/skill/1875/">[img src="/skills/cbt_ch_pentacleshock_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1875/" class="qtooltip item_grade_1"  data-id="skill--1875"><b>破裂击</b></a>',
    30,
    "使用",
    "护法星",
    2,
  ],
  [
    1700,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1700"><div class="icon_wrapper"><a href="/cn/skill/1700/">[img src="/skills/live_ch_presssmash_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1700/" class="qtooltip item_grade_1"  data-id="skill--1700"><b>粉碎一击</b></a>',
    30,
    "使用",
    "护法星",
    2,
  ],
  [
    1690,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1690"><div class="icon_wrapper"><a href="/cn/skill/1690/">[img src="/skills/live_ch_protectself_g8.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1690/" class="qtooltip item_grade_1"  data-id="skill--1690"><b>保护阵</b></a>',
    10,
    "使用",
    "护法星",
    2,
  ],
  [
    1810,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1810"><div class="icon_wrapper"><a href="/cn/skill/1810/">[img src="/skills/cbt_ch_crusader_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1810/" class="qtooltip item_grade_1"  data-id="skill--1810"><b>疾风之咒语</b></a>',
    10,
    "使用",
    "护法星",
    2,
  ],
  [
    1768,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1768"><div class="icon_wrapper"><a href="/cn/skill/1768/">[img src="/skills/ch_rapidthrust_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1768/" class="qtooltip item_grade_1"  data-id="skill--1768"><b>连续击破</b></a>',
    10,
    "使用",
    "护法星",
    2,
  ],
  [
    1601,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1601"><div class="icon_wrapper"><a href="/cn/skill/1601/">[img src="/skills/live_ch_renewedvitality_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1601/" class="qtooltip item_grade_1"  data-id="skill--1601"><b>力量释放</b></a>',
    70,
    "使用",
    "护法星",
    2,
  ],
  [
    1798,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1798"><div class="icon_wrapper"><a href="/cn/skill/1798/">[img src="/skills/live_ch_shockattack_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1798/" class="qtooltip item_grade_1"  data-id="skill--1798"><b>振动连锁</b></a>',
    50,
    "使用",
    "护法星",
    2,
  ],
  [
    1580,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1580"><div class="icon_wrapper"><a href="/cn/skill/1580/">[img src="/skills/cbt_ch_sonicgenoside_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1580/" class="qtooltip item_grade_1"  data-id="skill--1580"><b>共鸣烟雾</b></a>',
    30,
    "使用",
    "护法星",
    2,
  ],
  [
    1562,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1562"><div class="icon_wrapper"><a href="/cn/skill/1562/">[img src="/skills/cbt_ch_sonicswing_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1562/" class="qtooltip item_grade_1"  data-id="skill--1562"><b>击破连锁</b></a>',
    10,
    "使用",
    "护法星",
    2,
  ],
  [
    1757,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1757"><div class="icon_wrapper"><a href="/cn/skill/1757/">[img src="/skills/ch_spaceescape_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1757/" class="qtooltip item_grade_1"  data-id="skill--1757"><b>时空逃脱</b></a>',
    70,
    "使用",
    "护法星",
    2,
  ],
  [
    1858,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1858"><div class="icon_wrapper"><a href="/cn/skill/1858/">[img src="/skills/live_ch_stigma_recoverword_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1858/" class="qtooltip item_grade_1"  data-id="skill--1858"><b>痊愈之咒语</b></a>',
    20,
    "使用",
    "护法星",
    2,
  ],
  [
    1639,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1639"><div class="icon_wrapper"><a href="/cn/skill/1639/">[img src="/skills/ch_tearingcrash_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1639/" class="qtooltip item_grade_1"  data-id="skill--1639"><b>强力击</b></a>',
    20,
    "使用",
    "护法星",
    2,
  ],
  [
    1703,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1703"><div class="icon_wrapper"><a href="/cn/skill/1703/">[img src="/skills/ch_tearingstrike_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1703/" class="qtooltip item_grade_1"  data-id="skill--1703"><b>分裂一击</b></a>',
    20,
    "使用",
    "护法星",
    2,
  ],
  [
    1667,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1667"><div class="icon_wrapper"><a href="/cn/skill/1667/">[img src="/skills/cbt_ch_triangleshock_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1667/" class="qtooltip item_grade_1"  data-id="skill--1667"><b>白热一击</b></a>',
    30,
    "使用",
    "护法星",
    2,
  ],
  [
    1778,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1778"><div class="icon_wrapper"><a href="/cn/skill/1778/">[img src="/skills/cbt_ch_violentswing_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1778/" class="qtooltip item_grade_1"  data-id="skill--1778"><b>流星一击</b></a>',
    10,
    "使用",
    "护法星",
    2,
  ],
  [
    1758,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1758"><div class="icon_wrapper"><a href="/cn/skill/1758/">[img src="/skills/cbt_ch_zest_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1758/" class="qtooltip item_grade_1"  data-id="skill--1758"><b>神速之咒语</b></a>',
    50,
    "使用",
    "护法星",
    2,
  ],
  [
    4685,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--4685"><div class="icon_wrapper"><a href="/cn/skill/4685/">[img src="/skills/live_ch_stigma_angelicwall_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/4685/" class="qtooltip item_grade_1"  data-id="skill--4685"><b>阻断之幕</b></a>',
    50,
    "使用",
    "护法星",
    2,
  ],
  [
    5111,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5111"><div class="icon_wrapper"><a href="/cn/skill/5111/">[img src="/skills/ch_mortalstrike_custom_a.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5111/" class="qtooltip item_grade_1"  data-id="skill--5111"><b>贯通波</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5112,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5112"><div class="icon_wrapper"><a href="/cn/skill/5112/">[img src="/skills/ch_mortalstrike_custom_b.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5112/" class="qtooltip item_grade_1"  data-id="skill--5112"><b>贯通·猛</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5113,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5113"><div class="icon_wrapper"><a href="/cn/skill/5113/">[img src="/skills/ch_recoverword_custom_a.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5113/" class="qtooltip item_grade_1"  data-id="skill--5113"><b>痊愈之净化咒语</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5114,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5114"><div class="icon_wrapper"><a href="/cn/skill/5114/">[img src="/skills/ch_recoverword_custom_b.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5114/" class="qtooltip item_grade_1"  data-id="skill--5114"><b>痊愈之保护咒语</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5115,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5115"><div class="icon_wrapper"><a href="/cn/skill/5115/">[img src="/skills/ch_rapidthrust_custom_a.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5115/" class="qtooltip item_grade_1"  data-id="skill--5115"><b>连环斩</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5116,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5116"><div class="icon_wrapper"><a href="/cn/skill/5116/">[img src="/skills/ch_rapidthrust_custom_b.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5116/" class="qtooltip item_grade_1"  data-id="skill--5116"><b>连续猛击</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5175,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5175"><div class="icon_wrapper"><a href="/cn/skill/5175/">[img src="/skills/ch_sonicgenoside_custom_a.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5175/" class="qtooltip item_grade_1"  data-id="skill--5175"><b>共鸣悲雾</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5265,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5265"><div class="icon_wrapper"><a href="/cn/skill/5265/">[img src="/skills/ch_sonicgenoside_custom_b.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5265/" class="qtooltip item_grade_1"  data-id="skill--5265"><b>强化共鸣悲雾</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5266,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5266"><div class="icon_wrapper"><a href="/cn/skill/5266/">[img src="/skills/ch_sonicgenoside_custom_c.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5266/" class="qtooltip item_grade_1"  data-id="skill--5266"><b>共鸣连斩</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5281,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5281"><div class="icon_wrapper"><a href="/cn/skill/5281/">[img src="/skills/ch_presssmash_custom_a.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5281/" class="qtooltip item_grade_1"  data-id="skill--5281"><b>魂碎击</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5282,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5282"><div class="icon_wrapper"><a href="/cn/skill/5282/">[img src="/skills/ch_presssmash_custom_b.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5282/" class="qtooltip item_grade_1"  data-id="skill--5282"><b>斩碎击</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5768,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5768"><div class="icon_wrapper"><a href="/cn/skill/5768/">[img src="/skills/ch_mortalstrike_custom_a_up.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5768/" class="qtooltip item_grade_1"  data-id="skill--5768"><b>（提高）贯通波</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5769,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5769"><div class="icon_wrapper"><a href="/cn/skill/5769/">[img src="/skills/ch_mortalstrike_custom_b_up.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5769/" class="qtooltip item_grade_1"  data-id="skill--5769"><b>（提高）贯通·猛</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5770,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5770"><div class="icon_wrapper"><a href="/cn/skill/5770/">[img src="/skills/ch_recoverword_custom_a_up.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5770/" class="qtooltip item_grade_1"  data-id="skill--5770"><b>（提高）痊愈之净化咒语</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5771,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5771"><div class="icon_wrapper"><a href="/cn/skill/5771/">[img src="/skills/ch_recoverword_custom_b_up.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5771/" class="qtooltip item_grade_1"  data-id="skill--5771"><b>（提高）痊愈之保护咒语</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5772,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5772"><div class="icon_wrapper"><a href="/cn/skill/5772/">[img src="/skills/ch_rapidthrust_custom_a_up.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5772/" class="qtooltip item_grade_1"  data-id="skill--5772"><b>（提高）连环斩</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5773,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5773"><div class="icon_wrapper"><a href="/cn/skill/5773/">[img src="/skills/ch_rapidthrust_custom_b_up.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5773/" class="qtooltip item_grade_1"  data-id="skill--5773"><b>（提高）连续猛击</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5774,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5774"><div class="icon_wrapper"><a href="/cn/skill/5774/">[img src="/skills/ch_sonicgenoside_custom_b_up.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5774/" class="qtooltip item_grade_1"  data-id="skill--5774"><b>（提高）强化共鸣悲雾</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5775,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5775"><div class="icon_wrapper"><a href="/cn/skill/5775/">[img src="/skills/ch_sonicgenoside_custom_c_up.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5775/" class="qtooltip item_grade_1"  data-id="skill--5775"><b>（提高）共鸣连斩</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5776,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5776"><div class="icon_wrapper"><a href="/cn/skill/5776/">[img src="/skills/ch_presssmash_custom_a_up.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5776/" class="qtooltip item_grade_1"  data-id="skill--5776"><b>（提高）魂碎击</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5777,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5777"><div class="icon_wrapper"><a href="/cn/skill/5777/">[img src="/skills/ch_presssmash_custom_b_up.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5777/" class="qtooltip item_grade_1"  data-id="skill--5777"><b>（提高）斩碎击</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5993,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5993"><div class="icon_wrapper"><a href="/cn/skill/5993/">[img src="/skills/ev_ch_protectself_custom_a.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5993/" class="qtooltip item_grade_1"  data-id="skill--5993"><b>恢复守护阵</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5994,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5994"><div class="icon_wrapper"><a href="/cn/skill/5994/">[img src="/skills/ev_ch_protectself_custom_b.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5994/" class="qtooltip item_grade_1"  data-id="skill--5994"><b>抵抗守护阵</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5995,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5995"><div class="icon_wrapper"><a href="/cn/skill/5995/">[img src="/skills/ev_ch_protectself_custom_a_up.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5995/" class="qtooltip item_grade_1"  data-id="skill--5995"><b>（增强）恢复守护阵</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    5996,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--5996"><div class="icon_wrapper"><a href="/cn/skill/5996/">[img src="/skills/ev_ch_protectself_custom_b_up.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/5996/" class="qtooltip item_grade_1"  data-id="skill--5996"><b>（增强）抵抗守护阵</b></a>',
    80,
    "使用",
    "护法星",
    2,
  ],
  [
    4012,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--4012"><div class="icon_wrapper"><a href="/cn/skill/4012/">[img src="/skills/cbt_cl_smite_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/4012/" class="qtooltip item_grade_1"  data-id="skill--4012"><b>大地的报应</b></a>',
    10,
    "使用",
    "护法星",
    2,
  ],
  [
    1684,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1684"><div class="icon_wrapper"><a href="/cn/skill/1684/">[img src="/skills/cbt_cl_blessofrock_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1684/" class="qtooltip item_grade_1"  data-id="skill--1684"><b>保护祝福</b></a>',
    10,
    "使用",
    "护法星",
    2,
  ],
  [
    1814,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1814"><div class="icon_wrapper"><a href="/cn/skill/1814/">[img src="/skills/cbt_cl_soniceruption_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1814/" class="qtooltip item_grade_1"  data-id="skill--1814"><b>天罚</b></a>',
    10,
    "使用",
    "护法星",
    2,
  ],
  [
    6692,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--6692"><div class="icon_wrapper"><a href="/cn/skill/6692/">[img src="/skills/ch_tearingcrash_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/6692/" class="qtooltip item_grade_1"  data-id="skill--6692"><b>强化强力击</b></a>',
    84,
    "使用",
    "护法星",
    2,
  ],
  [
    6693,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--6693"><div class="icon_wrapper"><a href="/cn/skill/6693/">[img src="/skills/live_ch_chakra_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/6693/" class="qtooltip item_grade_1"  data-id="skill--6693"><b>强化气力重生</b></a>',
    84,
    "使用",
    "护法星",
    2,
  ],
  [
    6694,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--6694"><div class="icon_wrapper"><a href="/cn/skill/6694/">[img src="/skills/live_ch_stigma_angelicwall_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/6694/" class="qtooltip item_grade_1"  data-id="skill--6694"><b>强化阻断之幕</b></a>',
    84,
    "使用",
    "护法星",
    2,
  ],
  [
    1684,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1684"><div class="icon_wrapper"><a href="/cn/skill/1684/">[img src="/skills/cbt_cl_blessofrock_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1684/" class="qtooltip item_grade_1"  data-id="skill--1684"><b>保护祝福</b></a>',
    5,
    "使用",
    "治愈星, 护法星",
    2,
  ],
  [
    1614,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1614"><div class="icon_wrapper"><a href="/cn/skill/1614/">[img src="/skills/cbt_cl_hallowswing_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1614/" class="qtooltip item_grade_1"  data-id="skill--1614"><b>断罪一击</b></a>',
    3,
    "使用",
    "治愈星, 护法星",
    2,
  ],
  [
    1838,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1838"><div class="icon_wrapper"><a href="/cn/skill/1838/">[img src="/skills/cbt_cl_heal_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1838/" class="qtooltip item_grade_1"  data-id="skill--1838"><b>治愈之光</b></a>',
    1,
    "使用",
    "治愈星, 护法星",
    2,
  ],
  [
    4012,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--4012"><div class="icon_wrapper"><a href="/cn/skill/4012/">[img src="/skills/cbt_cl_smite_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/4012/" class="qtooltip item_grade_1"  data-id="skill--4012"><b>大地的报应</b></a>',
    1,
    "使用",
    "治愈星, 护法星",
    2,
  ],
  [
    1814,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1814"><div class="icon_wrapper"><a href="/cn/skill/1814/">[img src="/skills/cbt_cl_soniceruption_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1814/" class="qtooltip item_grade_1"  data-id="skill--1814"><b>天罚</b></a>',
    6,
    "使用",
    "治愈星, 护法星",
    2,
  ],
];

const temp2 = [
  [
    1756,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1756"><div class="icon_wrapper"><a href="/cn/skill/1756/">[img src="/skills/live_ch_blessprotect_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1756/" class="qtooltip item_grade_1"  data-id="skill--1756"><b>守护之祝福</b></a>',
    45,
    "上级烙印之石",
    "护法星",
    2,
  ],
  [
    1801,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1801"><div class="icon_wrapper"><a href="/cn/skill/1801/">[img src="/skills/live_ch_encouragerun_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1801/" class="qtooltip item_grade_1"  data-id="skill--1801"><b>疾行激励</b></a>',
    20,
    "普通烙印之石",
    "护法星",
    2,
  ],
  [
    1651,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1651"><div class="icon_wrapper"><a href="/cn/skill/1651/">[img src="/skills/live_ch_imbuepower_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1651/" class="qtooltip item_grade_1"  data-id="skill--1651"><b>风之祝福</b></a>',
    45,
    "上级烙印之石",
    "护法星",
    2,
  ],
  [
    1576,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1576"><div class="icon_wrapper"><a href="/cn/skill/1576/">[img src="/skills/cbt_ch_improvedallattack_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1576/" class="qtooltip item_grade_1"  data-id="skill--1576"><b>鼓吹之咒语</b></a>',
    20,
    "普通烙印之石",
    "护法星",
    2,
  ],
  [
    1755,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1755"><div class="icon_wrapper"><a href="/cn/skill/1755/">[img src="/skills/cbt_ch_improvedalldefend_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1755/" class="qtooltip item_grade_1"  data-id="skill--1755"><b>守护之咒语</b></a>',
    45,
    "上级烙印之石",
    "护法星",
    2,
  ],
  [
    1832,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1832"><div class="icon_wrapper"><a href="/cn/skill/1832/">[img src="/skills/live_ch_improvedbody_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1832/" class="qtooltip item_grade_1"  data-id="skill--1832"><b>铁壁之咒语</b></a>',
    55,
    "最高级烙印之石",
    "护法星",
    2,
  ],
  [
    1727,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1727"><div class="icon_wrapper"><a href="/cn/skill/1727/">[img src="/skills/cbt_ch_improvedlifestream_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1727/" class="qtooltip item_grade_1"  data-id="skill--1727"><b>生命之咒语</b></a>',
    20,
    "普通烙印之石",
    "护法星",
    2,
  ],
  [
    1869,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1869"><div class="icon_wrapper"><a href="/cn/skill/1869/">[img src="/skills/live_ch_mountaincrash_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1869/" class="qtooltip item_grade_1"  data-id="skill--1869"><b>破散击</b></a>',
    45,
    "上级烙印之石",
    "护法星",
    2,
  ],
  [
    1607,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1607"><div class="icon_wrapper"><a href="/cn/skill/1607/">[img src="/skills/live_ch_phoenixstep_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1607/" class="qtooltip item_grade_1"  data-id="skill--1607"><b>气概</b></a>',
    20,
    "普通烙印之石",
    "护法星",
    2,
  ],
  [
    1863,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1863"><div class="icon_wrapper"><a href="/cn/skill/1863/">[img src="/skills/live_ch_shockwave_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1863/" class="qtooltip item_grade_1"  data-id="skill--1863"><b>波动攻击</b></a>',
    45,
    "上级烙印之石",
    "护法星",
    2,
  ],
  [
    1835,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1835"><div class="icon_wrapper"><a href="/cn/skill/1835/">[img src="/skills/live_ch_slowcrash_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1835/" class="qtooltip item_grade_1"  data-id="skill--1835"><b>冲击锁</b></a>',
    55,
    "最高级烙印之石",
    "护法星",
    2,
  ],
  [
    1760,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1760"><div class="icon_wrapper"><a href="/cn/skill/1760/">[img src="/skills/live_ch_soaredrock_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1760/" class="qtooltip item_grade_1"  data-id="skill--1760"><b>暗击锁</b></a>',
    20,
    "普通烙印之石",
    "护法星",
    2,
  ],
  [
    1790,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1790"><div class="icon_wrapper"><a href="/cn/skill/1790/">[img src="/skills/live_ch_splashswing_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1790/" class="qtooltip item_grade_1"  data-id="skill--1790"><b>流水攻击</b></a>',
    20,
    "普通烙印之石",
    "护法星",
    2,
  ],
  [
    1852,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1852"><div class="icon_wrapper"><a href="/cn/skill/1852/">[img src="/skills/live_ch_surperiorheal_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1852/" class="qtooltip item_grade_1"  data-id="skill--1852"><b>痊愈之手</b></a>',
    45,
    "上级烙印之石",
    "护法星",
    2,
  ],
  [
    1883,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1883"><div class="icon_wrapper"><a href="/cn/skill/1883/">[img src="/skills/live_ch_thruststrike_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1883/" class="qtooltip item_grade_1"  data-id="skill--1883"><b>爆裂</b></a>',
    20,
    "普通烙印之石",
    "护法星",
    2,
  ],
  [
    1640,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1640"><div class="icon_wrapper"><a href="/cn/skill/1640/">[img src="/skills/live_ch_triplethrust_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1640/" class="qtooltip item_grade_1"  data-id="skill--1640"><b>灭火</b></a>',
    20,
    "普通烙印之石",
    "护法星",
    2,
  ],
  [
    1901,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1901"><div class="icon_wrapper"><a href="/cn/skill/1901/">[img src="/skills/ch_tornado_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1901/" class="qtooltip item_grade_1"  data-id="skill--1901"><b>狂风击</b></a>',
    55,
    "秘传烙印之石",
    "护法星",
    2,
  ],
  [
    1904,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1904"><div class="icon_wrapper"><a href="/cn/skill/1904/">[img src="/skills/ch_brand_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1904/" class="qtooltip item_grade_1"  data-id="skill--1904"><b>烙印咒语</b></a>',
    55,
    "秘传烙印之石",
    "护法星",
    2,
  ],
  [
    1907,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--1907"><div class="icon_wrapper"><a href="/cn/skill/1907/">[img src="/skills/ch_physicalenhancement_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/1907/" class="qtooltip item_grade_1"  data-id="skill--1907"><b>煽动咒语</b></a>',
    55,
    "秘传烙印之石",
    "护法星",
    2,
  ],
  [
    4615,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--4615"><div class="icon_wrapper"><a href="/cn/skill/4615/">[img src="/skills/ch_harshthrust_1_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/4615/" class="qtooltip item_grade_1"  data-id="skill--4615"><b>绝命重击</b></a>',
    20,
    "普通烙印之石",
    "护法星",
    2,
  ],
  [
    4631,
    '<div class="iconset_wrapper_big inlinediv qtooltip pointer" data-id="skill--4631"><div class="icon_wrapper"><a href="/cn/skill/4631/">[img src="/skills/cbt_ch_healingtank_g1.png" alt="icon" class="item_icon"]</a></div></div>',
    '<a href="/cn/skill/4631/" class="qtooltip item_grade_1"  data-id="skill--4631"><b>吸收之咒语</b></a>',
    20,
    "普通烙印之石",
    "护法星",
    2,
  ],
];

export function buildSkills() {
  const skillList: LibSkill[] = [];
  tempArr.forEach((arr) => {
    const regex = /<b>(.*?)<\/b>/;

    const match = (arr[2] as string).match(regex);
    skillList.push({
      id: arr[0] as number,
      name: match?.[1] ?? "",
      level: arr[3] as number,
      type: arr[4] as string,
      role: (arr[5] as string).split(", "),
    });
  });

  temp2.forEach((arr) => {
    const regex = /<b>(.*?)<\/b>/;

    const match = (arr[2] as string).match(regex);
    skillList.push({
      id: arr[0] as number,
      name: match?.[1] ?? "",
      level: arr[3] as number,
      type: arr[4] as string,
      role: (arr[5] as string).split(", "),
    });
  });


  return skillList;
}
