export const templarSkills = [
  {
    id: 246,
    name: "药草治疗",
    level: 10,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3094,
    name: "盾牌反击",
    level: 10,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 2981,
    name: "挑衅",
    level: 10,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3072,
    name: "盾牌重击",
    level: 40,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3123,
    name: "捕获",
    level: 30,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3085,
    name: "惩戒一击 ",
    level: 20,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3129,
    name: "主神之盔甲",
    level: 20,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3055,
    name: "无力之猛击",
    level: 10,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3038,
    name: "必灭一击",
    level: 30,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3131,
    name: "连续乱打",
    level: 10,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3010,
    name: "挑衅的咆哮",
    level: 10,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3124,
    name: "突击",
    level: 60,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 2932,
    name: "均衡的盔甲",
    level: 50,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3106,
    name: "盾牌突击",
    level: 40,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3116,
    name: "脚踝重击",
    level: 30,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3140,
    name: "审判",
    level: 30,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 2975,
    name: "战友保护",
    level: 50,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3127,
    name: "双重盔甲",
    level: 50,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3162,
    name: "罗网",
    level: 10,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 283,
    name: "解除冲击",
    level: 40,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3128,
    name: "快速盾",
    level: 70,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3168,
    name: "内扎坎之盾",
    level: 50,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 2933,
    name: "破坏之气合",
    level: 40,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3113,
    name: "盾牌打击",
    level: 50,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3071,
    name: "活捉",
    level: 50,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3066,
    name: "极限猛击",
    level: 40,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3084,
    name: "盾牌连击",
    level: 50,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3048,
    name: "威胁姿态",
    level: 60,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3069,
    name: "守护之甲",
    level: 70,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 3125,
    name: "剑风",
    level: 50,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 2967,
    name: "幻影摄捕",
    level: 40,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 4672,
    name: "风剑斩",
    level: 20,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5087,
    name: "战友守护",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5088,
    name: "战友庇护",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5089,
    name: "盾牌乱击",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5090,
    name: "盾牌猛攻",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5091,
    name: "双重挑衅盔甲",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5092,
    name: "双重铁甲",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5169,
    name: "脚踝粉碎",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5253,
    name: "强化脚踝粉碎",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5254,
    name: "脚踝刺击",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5275,
    name: "旋风劈裂",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5276,
    name: "吸收斩",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5728,
    name: "（提高）战友守护",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5729,
    name: "（提高）战友庇护",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5730,
    name: "（提高）盾牌乱击",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5731,
    name: "（提高）盾牌猛攻",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5732,
    name: "（提高）双重挑衅盔甲",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5733,
    name: "（提高）双重铁甲",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5734,
    name: "（提高）强化脚踝粉碎",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5735,
    name: "（提高）脚踝刺击",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5736,
    name: "（提高）旋风劈裂",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5737,
    name: "（提高）吸收斩",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5973,
    name: "多重捕捉",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5974,
    name: "集中捕捉",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5975,
    name: "（增强）多重捕捉",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 5976,
    name: "（增强）集中捕捉",
    level: 80,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 2903,
    name: "气合",
    level: 10,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 6686,
    name: "强化快速摄捕",
    level: 84,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 6687,
    name: "强化均衡的盔甲",
    level: 84,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 6688,
    name: "强化吸血一击",
    level: 84,
    type: "使用",
    role: ["守护星"],
  },
  {
    id: 517,
    name: "剑气挑衅",
    level: 6,
    type: "使用",
    role: ["剑星", "守护星"],
  },
  {
    id: 2864,
    name: "猛烈一击",
    level: 1,
    type: "使用",
    role: ["剑星", "守护星"],
  },
  {
    id: 2877,
    name: "会心一击",
    level: 3,
    type: "使用",
    role: ["剑星", "守护星"],
  },
  {
    id: 2890,
    name: "身体重击",
    level: 5,
    type: "使用",
    role: ["剑星", "守护星"],
  },
  {
    id: 2903,
    name: "气合",
    level: 6,
    type: "使用",
    role: ["剑星", "守护星"],
  },
  {
    id: 2961,
    name: "保护之盾",
    level: 20,
    type: "普通烙印之石",
    role: ["守护星"],
  },
  {
    id: 3035,
    name: "激昂",
    level: 20,
    type: "普通烙印之石",
    role: ["守护星"],
  },
  {
    id: 2945,
    name: "愤怒诱发",
    level: 20,
    type: "普通烙印之石",
    role: ["守护星"],
  },
  {
    id: 2993,
    name: "反击防御",
    level: 20,
    type: "普通烙印之石",
    role: ["守护星"],
  },
  {
    id: 3147,
    name: "处决一击",
    level: 20,
    type: "普通烙印之石",
    role: ["守护星"],
  },
  {
    id: 649,
    name: "破坏城门",
    level: 20,
    type: "普通烙印之石",
    role: ["守护星"],
  },
  {
    id: 3174,
    name: "惩罚",
    level: 20,
    type: "普通烙印之石",
    role: ["守护星"],
  },
  {
    id: 2934,
    name: "阻断之甲",
    level: 20,
    type: "普通烙印之石",
    role: ["守护星"],
  },
  {
    id: 2953,
    name: "天雷斩",
    level: 20,
    type: "普通烙印之石",
    role: ["守护星"],
  },
  {
    id: 3155,
    name: "复活",
    level: 45,
    type: "上级烙印之石",
    role: ["守护星"],
  },
  {
    id: 2926,
    name: "庇护之盔甲",
    level: 45,
    type: "上级烙印之石",
    role: ["守护星"],
  },
  {
    id: 2939,
    name: "精神破坏",
    level: 45,
    type: "上级烙印之石",
    role: ["守护星"],
  },
  {
    id: 3049,
    name: "魔力重击",
    level: 45,
    type: "上级烙印之石",
    role: ["守护星"],
  },
  {
    id: 2968,
    name: "束缚波",
    level: 45,
    type: "上级烙印之石",
    role: ["守护星"],
  },
  {
    id: 2974,
    name: "坚固的盾牌",
    level: 45,
    type: "上级烙印之石",
    role: ["守护星"],
  },
  {
    id: 2922,
    name: "主神的保护",
    level: 55,
    type: "最高级烙印之石",
    role: ["守护星"],
  },
  {
    id: 2923,
    name: "破灭之盾",
    level: 55,
    type: "最高级烙印之石",
    role: ["守护星"],
  },
  {
    id: 2919,
    name: "嗜魂惩罚",
    level: 55,
    type: "秘传烙印之石",
    role: ["守护星"],
  },
  {
    id: 2915,
    name: "守护之盾",
    level: 55,
    type: "秘传烙印之石",
    role: ["守护星"],
  },
  {
    id: 2918,
    name: "惩戒反射",
    level: 55,
    type: "秘传烙印之石",
    role: ["守护星"],
  },
];
